INSERT INTO posts (user_id, usr_type_id, name, name_ES, slug, image, content, content_ES, enabled)  /*se genera el post*/
VALUES (1, 1, 'Diabetes mellitus: The epidemic of the century', 'Diabetes mellitus: la epidemia del siglo', 'diabetes-mellitus',
'https://revistadiabetespr.com/wp-content/uploads/2019/09/diabetes-mellitus.jpg', 'The epidemic nature of diabetes mellitus in different regions is reviewed. The Middle East and North Africa region has the highest prevalence of diabetes in adults (10.9%) whereas, the Western Pacific region has the highest number of adults diagnosed with diabetes and has countries with the highest prevalence of diabetes (37.5%). Different classes of diabetes mellitus, type 1, type 2, gestational diabetes and other types of diabetes mellitus are compared in terms of diagnostic criteria, etiology and genetics. Read more here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4478580/',
'Se revisa la naturaleza epidémica de la diabetes mellitus en diferentes regiones. La región de Oriente Medio y África del Norte tiene la mayor prevalencia de diabetes en adultos (10,9%), mientras que la región del Pacífico Occidental tiene el mayor número de adultos diagnosticados con diabetes y tiene países con la mayor prevalencia de diabetes (37,5%). Se comparan diferentes clases de diabetes mellitus, tipo 1, tipo 2, diabetes gestacional y otros tipos de diabetes mellitus en términos de criterios de diagnóstico, etiología y genética. Lea más aquí: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4478580/', 1);

INSERT INTO posts (user_id, usr_type_id, name, name_ES, slug, image, content, content_ES, enabled)  /*se genera el post*/
VALUES (1, 1, 'An overview of diabetes types and treatments.', 'Una descripción general de los tipos y tratamientos de la diabetes.', 'types-and-treatments-of-diabetes',
'https://www.mycirclecare.com/wp-content/uploads/2018/02/Types-of-diabetes.jpg', 'In the United States, the estimated number of people over 18 years of age with diagnosed and undiagnosed diabetes is 30.2 million. The figure represents between 27.9 and 32.7 percent of the population. Without ongoing, careful management, diabetes can lead to a buildup of sugars in the blood, which can increase the risk of dangerous complications, including stroke and heart disease. Different kinds of diabetes can occur, and managing the condition depends on the type. Not all forms of diabetes stem from a person being overweight or leading an inactive lifestyle. In fact, some are present from childhood. Read more here: https://www.medicalnewstoday.com/articles/323627',
'En los Estados Unidos, el número estimado de personas mayores de 18 años con diabetes diagnosticada y no diagnosticada es de 30,2 millones. La cifra representa entre el 27,9 y el 32,7 por ciento de la población. Sin un control continuo y cuidadoso, la diabetes puede provocar una acumulación de azúcares en la sangre, lo que puede aumentar el riesgo de complicaciones peligrosas, como accidentes cerebrovasculares y enfermedades cardíacas. Pueden ocurrir diferentes tipos de diabetes y el manejo de la afección depende del tipo. No todas las formas de diabetes se deben a que una persona tiene sobrepeso o lleva un estilo de vida inactivo. De hecho, algunos están presentes desde la infancia. Lea más aquí: https://www.medicalnewstoday.com/articles/323627', 1);

INSERT INTO posts (user_id, usr_type_id, name, name_ES, slug, image, content, content_ES, enabled)  /*se genera el post*/
VALUES (1, 1, 'Pharmacologic Approaches to Glycemic Treatment: Standards of Medical Care in Diabetes—2021', 'Enfoques farmacológicos para el tratamiento glucémico: estándares de atención médica en diabetes — 2021', 'Glycemic-Treatment',
'https://assets.aboutkidshealth.ca/AKHAssets/low_glycemic_index_treatment_for_epilepsy.jpg?renditionid=21', 'The American Diabetes Association (ADA) “Standards of Medical Care in Diabetes” includes the ADAs current clinical practice recommendations and is intended to provide the components of diabetes care, general treatment goals and guidelines, and tools to evaluate quality of care. Read more here: https://care.diabetesjournals.org/content/44/Supplement_1/S111',
'Los “Estándares de atención médica en diabetes” de la Asociación Estadounidense de Diabetes (ADA) incluyen las recomendaciones de práctica clínica actuales de la ADA y están destinadas a proporcionar los componentes de la atención de la diabetes, las metas y pautas generales del tratamiento y las herramientas para evaluar la calidad de la atención. Lea más aquí: https://care.diabetesjournals.org/content/44/Supplement_1/S111', 1);
